### ISSUE TITLE
tensorboard: got error message

### ISSUE THREAD

**Issue by XiaoxueZang** [tensorflow/nmt#176] opened 2017-11-15 16:52 UTC
During training, I want to open the Tensorboard by "tensorboard --port 22222 --logdir model_dir", but I got the following error message.
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --debug before flags were parsed.
I wonder how to fix it? Thank you!

**Comment by emorisse** [comment] 2017-11-20 15:52
Also seeing the same.

<pre>
$ /Users/emorisse/src/py3/bin/tensorboard --logdir checkpoints  
Traceback (most recent call last):
  File "/Users/emorisse/src/py3/bin/tensorboard", line 11, in <module>
    sys.exit(main())
  File "/Users/emorisse/src/py3/lib/python3.6/site-packages/tensorboard/main.py", line 44, in main
    return program.main(default.get_plugins(),
  File "/Users/emorisse/src/py3/lib/python3.6/site-packages/tensorboard/default.py", line 71, in get_plugins
    debugger = debugger_plugin_loader.get_debugger_plugin()
  File "/Users/emorisse/src/py3/lib/python3.6/site-packages/tensorboard/plugins/debugger/debugger_plugin_loader.py", line 46, in get_debugger_plugin
    if FLAGS.debugger_data_server_grpc_port is None:
  File "/Users/emorisse/src/py3/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 509, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --debugger_data_server_grpc_port before flags were parsed.
</pre>

Python 3.6.2
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc3)

Tensorflow compiled from source on OSX.

**Comment by jart** [comment] 2017-11-21 21:08
I recommend closing this issue out and following https://github.com/tensorflow/tensorboard/issues/764, since the problem is on TensorBoard's end and we're fixing it right now.

**Closed** 2017-11-23 20:27 UTC

**Comment by emorisse** [comment] 2017-11-24 17:35
Confirming: updating tb-nightly per tensorflow/tensorboard#764 did solve the problem I saw. 

Thank you.

**Comment by XiaoxueZang** [comment] 2017-11-24 17:44
@jart Thank you for all the help, but it does not work for me. I have the following error message:
Do you know any possible solutions? Thank you!
`Traceback (most recent call last):
  File "/Users/zangxiaoxue/anaconda/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/Users/zangxiaoxue/anaconda/lib/python3.5/site-packages/tensorboard/main.py", line 28, in <module>
    import tensorflow as tf
  File "/Users/zangxiaoxue/anaconda/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/zangxiaoxue/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/zangxiaoxue/anaconda/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/Users/zangxiaoxue/anaconda/lib/python3.5/site-packages/google/protobuf/descriptor_pb2.py", line 735, in <module>
    options=None, file=DESCRIPTOR),
  File "/Users/zangxiaoxue/anaconda/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start"`

**Comment by jart** [comment] 2017-11-24 18:39
Protobuf is having double double toil and trouble right now. See https://github.com/tensorflow/tensorflow/issues/12326.
